### ISSUE TITLE
Snes contoller error

### ISSUE THREAD

**Issue by When-Suddenly** [timville85/TripleController#3]
So basically I built this project a year ago, confirmed it working, got busy, and forgot about it until now. I only have 2 SNES controllers to test with this but was gaming fine in the past. Unfortunately, I am getting an error where no buttons work except the B button... and the B button inputs to all buttons except button 9. I re-tested all my leads and confirmed them working correctly, anyone know if there is a driver issue about this? Thanks for your time.

**Comment by timville85** [comment]
Very strange for something to work for a while and then stop working without using it... Anything potentially shorted on the Arduino?

Have you tried the new V2 project? It's backwards compatible with V1 boards.

**Comment by When-Suddenly** [comment]
sorry what is the V2 project? I am unaware of its existence

**Comment by timville85** [comment]
V2 project is here:

https://github.com/timville85/TripleController/tree/main/TripleUSBController-V2.1

If you could capture a video of using the controller with some kind of display to show the buttons I could see what might be causing the issue (like the Windows Control Panel Game Controller display)

**Comment by timville85** [comment]
Closing issue due to age. Feel free to reopen if needed.
