### ISSUE TITLE
Error 302 when doing verify/compile

### ISSUE THREAD

**Issue by Veridor** [timville85/TripleController#4]
When tryig to update my board with the latest firmware, I first did a verify/compile in the Arduino IDE but I'm not getting a 302 error:

Arduino: 1.8.16 (Windows 10), Board: "SparkFun Pro Micro, ATmega32U4 (5V, 16 MHz)"

SegaController32U4.cpp:61:58: error: stray '\302' in program

   <title>TripleController/SegaController32U4.cpp at main · timville85/TripleController · GitHub</title>

                                                          ^

SegaController32U4.cpp:61:59: error: stray '\267' in program

   <title>TripleController/SegaController32U4.cpp at main · timville85/TripleController · GitHub</title>

                                                           ^

[ Edited to avoid long scroll ] 

TripleUSBController-V2.1:2652:74: error: expected unqualified-id before '<' token

           <td id="LC326" class="blob-code blob-code-inner js-file-line">}</td>

                                                                          ^

TripleUSBController-V2.1:2728:16: error: expected unqualified-id before numeric constant

         &copy; 2022 GitHub, Inc.

                ^~~~

exit status 1

stray '\302' in program

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by timville85** [comment]
Did you download the source files directly from the repo? It looks like it's trying to compile HTML code, not the Arduino C code.

Can you try building it using a standard Arduino Leonardo board type? It should be compatible.

**Comment by Veridor** [comment]
> Did you download the source files directly from the repo? It looks like it's trying to compile HTML code, not the Arduino C code.
> 
> Can you try building it using a standard Arduino Leonardo board type? It should be compatible.

Ahh that was my problem. I was right clicking the files and doing "save link as" instead of raw downloads. Rookie mistake, sorry about that.
